### PR TITLE
Fix bugs related to error messages

### LINKED ISSUE #299: Edit Command: Error message bug
1. For all commands the parameter ends with `...`, this implies we take in more than 1 parameter of the last parameter you stated. This is misleading and thus is a bug
2. `edit_p` gives a wrong NRIC for an example

`edit_a`
image

`edit_d`
image

`edit_p`
image

### LINKED ISSUE #300: Add Tag Command: Bug in error messages
1. All the parameters for the tag uses square brackets, implying that it is optional. This is wrong that field is not optional.
2. `add_tag_d` parameter is on a extra new line (Not sure if we can fix this)
3. `add_tag_p` parameter is NOT on a new line (Not sure if we can fix this)

`add_tag_a`
image

`add_tag_d`
image

`add_tag_p`
image

### PR DESCRIPTION
**Pull request by yanghengtang**
Closes #299 
Closes #300

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/PatientRemarkCommand.java [hunk 1]
```diff
@@ -23,9 +24,9 @@ public class PatientRemarkCommand extends Command {
             + "by the index number used in the last patient listing. "
             + "Existing remark will be overwritten by the input.\n"
             + "Parameters: INDEX (must be a positive integer) "
-            + "r\\ [REMARK]\n"
+            + PREFIX_REMARK + "REMARK\n"
             + "Example: " + COMMAND_WORD + " 1 "
-            + "r/ Patient to follow up in 1 month.";
+            + PREFIX_REMARK + "Patient to follow up in 1 month.";
```
Comment (cheeggered) [inline src/main/java/seedu/address/logic/commands/PatientRemarkCommand.java:29]: Can change the example remark to something that follows our suggested usage of remarks in the UG, eg. family history of diabetes.

File: src/main/java/seedu/address/logic/commands/DoctorRemarkCommand.java [hunk 2]
```diff
@@ -26,9 +26,9 @@ public class DoctorRemarkCommand extends Command {
             + "by the index number used in the last doctor listing. "
             + "Existing remark will be overwritten by the input.\n"
             + "Parameters: INDEX (must be a positive integer) "
-            + PREFIX_REMARK + " [REMARK]\n"
+            + PREFIX_REMARK + "[REMARK]\n"
```
Comment (derekjxtan) [inline src/main/java/seedu/address/logic/commands/DoctorRemarkCommand.java:29]: for this the square brackets should be around PREFIX_REMARK also right since its optional

**Review by mounilsankar — APPROVED** [review]
